version: "3.5"
services:
  sensor1:
    image: sensor
    environment:
      - ID=sensor1
      - PORT=8080
      - MAX=100
      - MIN=40
    ports:
      - "8080:8080"
    networks:
      - default
  sensor2:
    image: sensor
    environment:
      - ID=sensor2
      - PORT=8081
      - MAX=60
      - MIN=0
    ports:
      - "8081:8081"
    networks:
      - default
  consumer:
    image: subpub
    environment:
      - SENSORS=sensor1:8080,sensor2:8081
      - MQTT=mosquitto:1883
    networks:
      - default
    depends_on:
      - sensor1
      - sensor2
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ${PWD}/mosquitto:/mosquitto
    networks:
      - default
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
#      - INFLUXDB_ADMIN_USER=admin
#      - INFLUXDB_ADMIN_PASSWORD=password123
    networks:
      - default
  chronograf:
    image: chronograf
    ports:
      - '8888:8888'
    volumes:
      - chronograph-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
#      - INFLUXDB_USERNAME=admin
#      - INFLUXDB_PASSWORD=password123
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password123
volumes:
  influxdb-storage:
  chronograph-storage:
  grafana-storage:
networks:
  default:
